import { TCompany } from '@/types';

import { PROJECTS } from './projects';

export const COMPANIES: Record<string, TCompany> = {
  c4: {
    name: 'Browsec',
    descriptionKey: 'profile.companyDescriptions.c4',
    countries: ['Worldwide', 'USA'],
    startDate: '2024-07-01',
    endDate: '2025-08-01',
    position: 'Software Engineer',
    technologies: ['React', 'TypeScript', 'Electron', 'Cypress', 'Redux'],
    image: '/images/companies/browsec.png',
    isLead: false,
    projects: [PROJECTS.p7, PROJECTS.p6],
  },
  c3: {
    name: 'Etalon Group',
    descriptionKey: 'profile.companyDescriptions.c3',
    countries: ['Russia'],
    startDate: '2023-08-01',
    endDate: '2024-06-01',
    position: 'Lead Frontend Engineer',
    technologies: ['React', 'TypeScript', 'Cypress', 'Tanstack Query', 'Jotai'],
    image: '/images/companies/etalon.png',
    isLead: true,
    projects: [PROJECTS.p5],
  },
  c2: {
    name: 'GlassesUSA.com',
    descriptionKey: 'profile.companyDescriptions.c2',
    countries: ['USA', 'Israel', 'Russia'],
    startDate: '2021-01-01',
    endDate: '2023-07-01',
    position: 'Frontend Developer',
    technologies: ['React', 'TypeScript', 'React-testing-library', 'Jest', 'Redux'],
    image: '/images/companies/glassesusa.png',
    isLead: true,
    projects: [PROJECTS.p4, PROJECTS.p3],
  },
  c1: {
    name: 'Seo-TLT',
    descriptionKey: 'profile.companyDescriptions.c1',
    countries: ['Russia'],
    startDate: '2018-08-01',
    endDate: '2020-12-01',
    position: 'Frontend Web Developer',
    technologies: ['React', 'TypeScript', 'GraphQL', 'Apollo'],
    image: '/images/companies/seo-tlt.png',
    isLead: false,
    projects: [PROJECTS.p2, PROJECTS.p1],
  },
  c0: {
    name: 'KT.Team',
    descriptionKey: 'profile.companyDescriptions.c0',
    countries: ['Russia'],
    startDate: '2017-12-01',
    endDate: '2018-07-01',
    position: 'Project Manager',
    technologies: [],
    image: '/images/companies/kt-team.png',
    isLead: false,
    projects: [],
    isPM: true,
  },
};
