import {
  AutoFillExtensionIcon,
  BuilderPlatformIcon,
  GUSADesktopIcon,
  GUSAMobileIcon,
  LifeCalendarIcon,
  MegePlanIcon,
  PassportDealerIcon,
  SubscriptionTGBotIcon,
  VPNDesktopAppIcon,
  VPNExtensionIcon,
} from '@/icons';

import { HARD_SKILLS } from './skills';

export const PROJECTS = {
  p1: {
    name: 'VPN Desktop App',
    descriptionKey: 'profile.projectDescriptions.p7',
    companyId: 'c4',
    icon: VPNDesktopAppIcon,
    isLead: false,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.ElectronJS,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.BitBucket,
      HARD_SKILLS.Sass,
      HARD_SKILLS.Firebase,
      HARD_SKILLS.NPM,
    ],
  },

  p2: {
    name: 'VPN Browser Extension',
    descriptionKey: 'profile.projectDescriptions.p6',
    companyId: 'c4',
    icon: VPNExtensionIcon,
    isLead: false,
    technologies: [
      HARD_SKILLS.Lit,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.Selenium,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.Rollup,
      HARD_SKILLS.BitBucket,
      HARD_SKILLS.Sass,
      HARD_SKILLS.Firebase,
    ],
  },
  p3: {
    name: 'Federal Builder Platform',
    descriptionKey: 'profile.projectDescriptions.p5',
    companyId: 'c3',
    icon: BuilderPlatformIcon,
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.ModuleFederation,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Docker,
      HARD_SKILLS.StyledComponents,
      HARD_SKILLS.AntDesign,
      HARD_SKILLS.NPM,
    ],
  },
  p4: {
    name: 'Glasses Store Desktop',
    descriptionKey: 'profile.projectDescriptions.p3',
    companyId: 'c2',
    icon: GUSADesktopIcon,
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Jest,
      HARD_SKILLS.Docker,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.NPM,
    ],
  },
  p5: {
    name: 'Glasses Store Mobile',
    descriptionKey: 'profile.projectDescriptions.p4',
    companyId: 'c2',
    icon: GUSAMobileIcon,
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Docker,
      HARD_SKILLS.Rollup,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.GitHub,
    ],
  },
  p6: {
    name: 'Dealer Passport',
    descriptionKey: 'profile.projectDescriptions.p2',
    companyId: 'c1',
    icon: PassportDealerIcon,
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Apollo,
      HARD_SKILLS.GraphQL,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.Less,
      HARD_SKILLS.ESLint,
      HARD_SKILLS.Prettier,
      HARD_SKILLS.Git,
      HARD_SKILLS.GitLab,
    ],
  },
  p7: {
    name: 'MegaPlan',
    descriptionKey: 'profile.projectDescriptions.p1',
    companyId: 'c1',
    icon: MegePlanIcon,
    isLead: false,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.Less,
      HARD_SKILLS.REST,
      HARD_SKILLS.HTML,
      HARD_SKILLS.CSS,
      HARD_SKILLS.GitLab,
      HARD_SKILLS.Jira,
    ],
  },
};

export const OWN_PROJECTS = {
  op1: {
    name: 'Auto Fill chrome extension',
    descriptionKey: 'profile.ownProjectDescriptions.op1',
    icon: AutoFillExtensionIcon,
    technologies: [
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.CSS,
      HARD_SKILLS.Git,
      HARD_SKILLS.GitHub,
    ],
  },
  op2: {
    name: 'Subscription Telegram Bot',
    descriptionKey: 'profile.ownProjectDescriptions.op2',
    icon: SubscriptionTGBotIcon,
    technologies: [
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.Git,
      HARD_SKILLS.GitHub,
    ],
  },
  op3: {
    name: 'Life Calendar',
    descriptionKey: 'profile.ownProjectDescriptions.op3',
    icon: LifeCalendarIcon,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.Pixi,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.PWA,
      HARD_SKILLS.Vite,
      HARD_SKILLS.Stylus,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Figma,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.GitHub,
    ],
  },
};
