import {
  AutoFillExtensionIcon,
  BuilderPlatformIcon,
  GUSADesktopIcon,
  GUSAMobileIcon,
  LifeCalendarIcon,
  LogoIcon,
  MegePlanIcon,
  PassportDealerIcon,
  VPNDesktopAppIcon,
  VPNExtensionIcon,
} from '@/icons';

import { HARD_SKILLS } from './skills';

export const PROJECTS = {
  p7: {
    name: 'VPN Desktop App',
    descriptionKey: 'profile.projectDescriptions.p7',
    fullDescriptionKey: 'profile.projectFullDescriptions.p7',
    companyId: 'c4',
    icon: VPNDesktopAppIcon,
    photo: '/images/projects/VPNDesktopAppPhoto.jpg',
    video: '/videos/projects/VPNDesktopAppClip.mp4',
    isLead: false,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.ElectronJS,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.BitBucket,
      HARD_SKILLS.Sass,
      HARD_SKILLS.Firebase,
      HARD_SKILLS.NPM,
    ],
  },

  p6: {
    name: 'VPN Browser Extension',
    descriptionKey: 'profile.projectDescriptions.p6',
    fullDescriptionKey: 'profile.projectFullDescriptions.p6',
    companyId: 'c4',
    icon: VPNExtensionIcon,
    photo: '/images/projects/VPNExtensionPhoto.jpg',
    video: '/videos/projects/VPNExtensionClip.mp4',
    isLead: false,
    technologies: [
      HARD_SKILLS.Lit,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.Selenium,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.Rollup,
      HARD_SKILLS.BitBucket,
      HARD_SKILLS.Sass,
      HARD_SKILLS.Firebase,
    ],
  },
  p5: {
    name: 'Federal Builder Platform',
    descriptionKey: 'profile.projectDescriptions.p5',
    fullDescriptionKey: 'profile.projectFullDescriptions.p5',
    companyId: 'c3',
    icon: BuilderPlatformIcon,
    photo: '/images/projects/BuilderPlatformPhoto.jpg',
    video: '/videos/projects/BuilderPlatformClip.mp4',
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.ModuleFederation,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Docker,
      HARD_SKILLS.StyledComponents,
      HARD_SKILLS.AntDesign,
      HARD_SKILLS.NPM,
    ],
  },
  p4: {
    name: 'Glasses Store Desktop',
    descriptionKey: 'profile.projectDescriptions.p4',
    fullDescriptionKey: 'profile.projectFullDescriptions.p4',
    companyId: 'c2',
    icon: GUSADesktopIcon,
    photo: '/images/projects/GUSADesktopPhoto.jpg',
    video: '/videos/projects/GUSADesktopClip.mp4',
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Jest,
      HARD_SKILLS.Docker,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.NPM,
    ],
  },
  p3: {
    name: 'Glasses Store Mobile',
    descriptionKey: 'profile.projectDescriptions.p3',
    fullDescriptionKey: 'profile.projectFullDescriptions.p3',
    companyId: 'c2',
    icon: GUSAMobileIcon,
    photo: '/images/projects/GUSAMobilePhoto.jpg',
    video: '/videos/projects/GUSAMobileClip.mp4',
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Docker,
      HARD_SKILLS.Rollup,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.GitHub,
    ],
  },
  p2: {
    name: 'Dealer Passport',
    descriptionKey: 'profile.projectDescriptions.p2',
    fullDescriptionKey: 'profile.projectFullDescriptions.p2',
    companyId: 'c1',
    icon: PassportDealerIcon,
    photo: '/images/projects/passportDealerPhoto.jpg',
    video: '/videos/projects/passportDealerClip.mp4',
    isLead: true,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Apollo,
      HARD_SKILLS.GraphQL,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.Less,
      HARD_SKILLS.ESLint,
      HARD_SKILLS.Prettier,
      HARD_SKILLS.Git,
      HARD_SKILLS.GitLab,
    ],
  },
  p1: {
    name: 'MegaPlan',
    descriptionKey: 'profile.projectDescriptions.p1',
    fullDescriptionKey: 'profile.projectFullDescriptions.p1',
    companyId: 'c1',
    icon: MegePlanIcon,
    photo: '/images/projects/MegaPlanPhoto.jpg',
    video: '/videos/projects/MegaPlanClip.mp4',
    isLead: false,
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.Redux,
      HARD_SKILLS.Saga,
      HARD_SKILLS.Less,
      HARD_SKILLS.REST,
      HARD_SKILLS.HTML,
      HARD_SKILLS.CSS,
      HARD_SKILLS.GitLab,
      HARD_SKILLS.Jira,
    ],
  },
};

export const OWN_PROJECTS = {
  op3: {
    name: 'Life Calendar',
    descriptionKey: 'profile.ownProjectDescriptions.op3',
    fullDescriptionKey: 'profile.ownProjectFullDescriptions.op3',
    icon: LifeCalendarIcon,
    photo: '/images/projects/LifeCalendarPhoto.jpg',
    video: '/videos/projects/LifeCalendarClip.mp4',
    gitHub: 'https://github.com/RasVadim/Life-calendar',
    link: 'https://lcalendar.app',
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.Pixi,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.PWA,
      HARD_SKILLS.Vite,
      HARD_SKILLS.Stylus,
      HARD_SKILLS.TanstackQuery,
      HARD_SKILLS.Figma,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.GitHub,
    ],
  },
  op2: {
    name: 'Chrome extension + Telegram Bot',
    descriptionKey: 'profile.ownProjectDescriptions.op2',
    fullDescriptionKey: 'profile.ownProjectFullDescriptions.op2',
    icon: AutoFillExtensionIcon,
    photo: '/images/projects/AutoFillExtensionPhoto.jpg',
    video: '/videos/projects/AutoFillExtensionClip.mp4',
    technologies: [
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.CSS,
      HARD_SKILLS.Git,
      HARD_SKILLS.GitHub,
    ],
  },
  op1: {
    name: 'Bussines Card',
    descriptionKey: 'profile.ownProjectDescriptions.op1',
    fullDescriptionKey: 'profile.ownProjectFullDescriptions.op1',
    icon: LogoIcon,
    photo: '/images/projects/BussinesCardPhoto.jpg',
    video: '/videos/projects/BussinesCardClip.mp4',
    gitHub: 'https://github.com/RasVadim/Business-card',
    link: 'https://rasstrigin.vercel.app',
    technologies: [
      HARD_SKILLS.React,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Vite,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.Stylus,
      HARD_SKILLS.Figma,
      HARD_SKILLS.GitHub,
    ],
  },
};
