import { THardSkill } from '@/types';

export const SOFT_SKILLS = [
  { id: 's1', nameKey: 'profile.softs.communicativeness' },
  { id: 's8', nameKey: 'profile.softs.scrum' },
  { id: 's2', nameKey: 'profile.softs.attentiveness' },
  { id: 's5', nameKey: 'profile.softs.argumentation' },
  { id: 's3', nameKey: 'profile.softs.selfAnalysis' },
  { id: 's4', nameKey: 'profile.softs.independence' },
  { id: 's6', nameKey: 'profile.softs.mentorship' },
  { id: 's7', nameKey: 'profile.softs.onboarding' },
  { id: 's9', nameKey: 'profile.softs.teamwork' },
  { id: 's10', nameKey: 'profile.softs.discipline' },
];

export const HARD_SKILLS: Record<string, THardSkill> = {
  React: {
    name: 'React',
    icon: '/images/skills/React.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.react',
  },
  Vue: {
    name: 'Vue',
    icon: '/images/skills/Vue.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.vue',
  },
  Pixi: {
    name: 'Pixi-js',
    icon: '/images/skills/Pixijs.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.pixi',
  },
  Lit: {
    name: 'Lit-elements',
    icon: '/images/skills/Lit.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.lit',
  },
  TanstackQuery: {
    name: 'Tanstack-Query',
    icon: '/images/skills/TanstackQuery.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.tanstack',
  },
  Apollo: {
    name: 'Apollo',
    icon: '/images/skills/Apollo.png',
    showLabel: true,
    darkIcon: '/images/skills/ApolloDark.png',
    descriptionKey: 'profile.hardSkillDescriptions.apollo',
  },
  Redux: {
    name: 'Redux',
    icon: '/images/skills/Redux.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.redux',
  },
  Saga: {
    name: 'Saga',
    icon: '/images/skills/Saga.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.saga',
  },
  JavaScript: {
    name: 'JavaScript',
    icon: '/images/skills/JavaScript.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.javascript',
  },
  TypeScript: {
    name: 'TypeScript',
    icon: '/images/skills/TypeScript.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.typescript',
  },
  Git: {
    name: 'Git',
    icon: '/images/skills/Git.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.git',
  },
  Docker: {
    name: 'Docker',
    icon: '/images/skills/Docker.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.docker',
  },
  Lua: {
    name: 'Lua',
    icon: '/images/skills/Lua.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.lua',
  },
  Storybook: {
    name: 'Storybook',
    icon: '/images/skills/Storybook.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.storybook',
  },
  Nodejs: {
    name: 'Nodejs',
    icon: '/images/skills/Nodejs.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.nodejs',
  },
  HTML: {
    name: 'HTML',
    icon: '/images/skills/HTML5.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.html',
  },
  GitHub: {
    name: 'GitHub',
    icon: '/images/skills/GitHub.png',
    showLabel: false,
    darkIcon: '/images/skills/GitHubDark.png',
    descriptionKey: 'profile.hardSkillDescriptions.github',
  },
  GitLab: {
    name: 'GitLab',
    icon: '/images/skills/GitLab.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.gitlab',
  },
  BitBucket: {
    name: 'BitBucket',
    icon: '/images/skills/BitBucket.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.bitbucket',
  },
  NPM: {
    name: 'NPM',
    icon: '/images/skills/NPM.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.npm',
  },
  ESLint: {
    name: 'ESLint',
    icon: '/images/skills/ESLint.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.eslint',
  },
  Prettier: {
    name: 'Prettier',
    icon: '/images/skills/Prettier.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.prettier',
  },
  Figma: {
    name: 'Figma',
    icon: '/images/skills/Figma.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.figma',
  },
  Jira: {
    name: 'Jira',
    icon: '/images/skills/Jira.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.jira',
  },
  Slack: {
    name: 'Slack',
    icon: '/images/skills/Slack.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.slack',
  },
  StyledComponents: {
    name: 'Styled-components',
    icon: '/images/skills/StyledComponents.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.styled',
  },
  AntDesign: {
    name: 'Ant-design',
    icon: '/images/skills/AntDesign.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.antd',
  },
  Stylus: {
    name: 'Stylus',
    icon: '/images/skills/Stylus.png',
    showLabel: true,
    darkIcon: '/images/skills/StylusDark.png',
    descriptionKey: 'profile.hardSkillDescriptions.stylus',
  },
  Less: {
    name: 'Less',
    icon: '/images/skills/Less.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.less',
  },
  Sass: {
    name: 'Sass',
    icon: '/images/skills/Sass.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.sass',
  },
  CSS: {
    name: 'CSS',
    icon: '/images/skills/CSS3.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.css',
  },
  Vite: {
    name: 'Vite',
    icon: '/images/skills/Vite.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.vite',
  },
  Webpack: {
    name: 'Webpack',
    icon: '/images/skills/Webpack.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.webpack',
  },
  ModuleFederation: {
    name: 'Module Federation',
    icon: '/images/skills/ModuleFederation.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.moduleFederation',
  },
  ElectronJS: {
    name: 'Electron JS',
    icon: '/images/skills/Electron.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.electron',
  },
  Rollup: {
    name: 'Rollup',
    icon: '/images/skills/Rollup.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.rollup',
  },
  Jest: {
    name: 'Jest',
    icon: '/images/skills/Jest.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.jest',
  },
  Cypress: {
    name: 'Cypress',
    icon: '/images/skills/Cypress.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.cypress',
  },
  ReactTestingLibrary: {
    name: 'React Testing Library',
    icon: '/images/skills/ReactTestingLibrary.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.rtl',
  },
  Selenium: {
    name: 'Selenium',
    icon: '/images/skills/Selenium.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.selenium',
  },
  GraphQL: {
    name: 'GraphQL',
    icon: '/images/skills/GraphQL.png',
    showLabel: true,
    descriptionKey: 'profile.hardSkillDescriptions.graphql',
  },
  Firebase: {
    name: 'Firebase',
    icon: '/images/skills/Firebase.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.firebase',
  },
  REST: {
    name: 'REST',
    icon: '/images/skills/REST.png',
    showLabel: false,
    descriptionKey: 'profile.hardSkillDescriptions.rest',
  },
};

export const HARD_SKILL_CATEGORIES = [
  {
    id: 'h1',
    titleKey: 'profile.hardCategories.ui',
    items: [HARD_SKILLS.React, HARD_SKILLS.Vue, HARD_SKILLS.Pixi, HARD_SKILLS.Lit],
  },
  {
    id: 'h2',
    titleKey: 'profile.hardCategories.state',
    items: [HARD_SKILLS.TanstackQuery, HARD_SKILLS.Apollo, HARD_SKILLS.Redux, HARD_SKILLS.Saga],
  },
  {
    id: 'h3',
    titleKey: 'profile.hardCategories.common',
    items: [
      HARD_SKILLS.JavaScript,
      HARD_SKILLS.TypeScript,
      HARD_SKILLS.Git,
      HARD_SKILLS.Docker,
      HARD_SKILLS.Lua,
      HARD_SKILLS.Storybook,
      HARD_SKILLS.Nodejs,
      HARD_SKILLS.HTML,
      HARD_SKILLS.GitHub,
      HARD_SKILLS.GitLab,
      HARD_SKILLS.BitBucket,
      HARD_SKILLS.NPM,
      HARD_SKILLS.ESLint,
      HARD_SKILLS.Prettier,
      HARD_SKILLS.Figma,
      HARD_SKILLS.Jira,
      HARD_SKILLS.Slack,
    ],
  },
  {
    id: 'h4',
    titleKey: 'profile.hardCategories.styles',
    items: [
      HARD_SKILLS.StyledComponents,
      HARD_SKILLS.AntDesign,
      HARD_SKILLS.Stylus,
      HARD_SKILLS.Less,
      HARD_SKILLS.Sass,
      HARD_SKILLS.CSS,
    ],
  },
  {
    id: 'h5',
    titleKey: 'profile.hardCategories.bundlers',
    items: [
      HARD_SKILLS.Vite,
      HARD_SKILLS.Webpack,
      HARD_SKILLS.ModuleFederation,
      HARD_SKILLS.ElectronJS,
      HARD_SKILLS.Rollup,
    ],
  },
  {
    id: 'h6',
    titleKey: 'profile.hardCategories.tests',
    items: [
      HARD_SKILLS.Jest,
      HARD_SKILLS.Cypress,
      HARD_SKILLS.ReactTestingLibrary,
      HARD_SKILLS.Selenium,
    ],
  },
  {
    id: 'h7',
    titleKey: 'profile.hardCategories.api',
    items: [HARD_SKILLS.GraphQL, HARD_SKILLS.Firebase, HARD_SKILLS.REST],
  },
];
